---
- hosts: all
  become: true
  tasks:

    - name: Creates java directory
      file:
        path: /usr/java
        state: directory

    - name: Unzip JDK
      unarchive:
        src: jdk-7u80-linux-x64.tar.gz
        dest: /usr/java

    - name: Download CDH5 package
      get_url:
        url: http://archive.cloudera.com/cdh5/one-click-install/precise/amd64/cdh5-repository_1.0_all.deb
        dest: /vagrant
        force_basic_auth: yes

    - name: Install cdh5-repository.deb
      apt:
        deb: /vagrant/cdh5-repository_1.0_all.deb

    - name: Add Cloudera repository key
      apt_key:
        url: http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh/archive.key

    - name: Update apt packages
      apt:
        update_cache: yes
        force_apt_get: yes
    
    - name: Install Zookeeper
      apt: 
        name: zookeeper-server
        state: latest 

    - name: Creates zookeeper directory
      file:
        path: /var/lib/zookeeper
        state: directory

    - name: Set permissions
      command: chown -R zookeeper /var/lib/zookeeper/

    # - name: Change file ownership, group and permissions
    #   file:
    #     path: /var/lib/zookeeper/
    #     owner: foo
    #     group: foo
    #     mode: '0644'

    - name: Init zookeeper
      command: service zookeeper-server init --myid=1 --force

    - name: Start zookeeper service
      service:
        name: zookeeper-server
        state: started

    - name: Install jobtracker
      apt: 
        name: hadoop-0.20-mapreduce-jobtracker

    - name: Install namenode
      apt: 
        name: hadoop-hdfs-namenode
        



